# CI de Nível 04 - Pipeline Integrada ao build do código

# nome da pipeline
name: "Execução Integrada"

# gatilhos / triggers - regras de disparo
# gatilho manual = workflow_dispatch
# gatilho agendado = schedule
# gatilho por conclusão de outra pipeline = workflow_run
on:
    workflow_dispatch
#tarefas dentro da pipeline = jobs
jobs:
    #nome do job
    inspecao:
        # maquina onde o job vai rodar
        runs-on: ubuntu-latest

        # passos do job
        steps:
            # clone do projeto
            - uses: actions/checkout@v4

            # instalção do node
            - uses: actions/setup-node@v4
              with:
                  node-version: latest

            # instalação do Yarn
            - name: Instalando Yarn
              run: npm install -g yarn
            
            # instalação das dependências
            - name: Instalando dependências
              run: yarn

            # inspeciona  fazendo uma validação
            - name: Inspeção de código
              run: yarn lint
            
            # instalação dos Browsers do Playwright
            - name: Instalando Browsers do Playwright
              run: yarn playwright install
            
            # executar os testes e2e
            - name: Executando testes e2e
              run: yarn run e2e

            #
            - name: Check Allure version
              run: npx allure --version  

            # irá gerar o relatório na pipeline
            - name: Gerar relatório Allure
              if: always()
              run: |
              
            - name: Install Allure CLI
              run: npm install -g allure-commandline

            - name: Generate Allure Report
              run: allure generate allure-results --clean -o allure-report  
            
            # só consegui abrir o relatório é através do bash: allure open allure-report
            - name: Upload Allure Report
              if: always()
              uses: actions/upload-artifact@v4
              with:
                name: allure-report
                path: allure-report
                retention-days: 7
                
            #  Configurar o dorny/test-reporter
            - name: Publicar resultados dos testes
              if: always()
              uses: dorny/test-reporter@v3
              with:
                name: Playwright Tests
                path: results.xml
                reporter: java-junit






